# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/marco/OneDrive/Desktop/Project - CopyOLD/Block_Design/AXI_Merge/AXI_Merge.srcs/sources_1/bd/AXI_Merge/ip/AXI_Merge_rst_ps7_0_0M_0/AXI_Merge_rst_ps7_0_0M_0.xci
# IP: The module: 'AXI_Merge_rst_ps7_0_0M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marco/OneDrive/Desktop/Project - CopyOLD/Block_Design/AXI_Merge/AXI_Merge.gen/sources_1/bd/AXI_Merge/ip/AXI_Merge_rst_ps7_0_0M_0/AXI_Merge_rst_ps7_0_0M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Merge_rst_ps7_0_0M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marco/OneDrive/Desktop/Project - CopyOLD/Block_Design/AXI_Merge/AXI_Merge.gen/sources_1/bd/AXI_Merge/ip/AXI_Merge_rst_ps7_0_0M_0/AXI_Merge_rst_ps7_0_0M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Merge_rst_ps7_0_0M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marco/OneDrive/Desktop/Project - CopyOLD/Block_Design/AXI_Merge/AXI_Merge.gen/sources_1/bd/AXI_Merge/ip/AXI_Merge_rst_ps7_0_0M_0/AXI_Merge_rst_ps7_0_0M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Merge_rst_ps7_0_0M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/marco/OneDrive/Desktop/Project - CopyOLD/Block_Design/AXI_Merge/AXI_Merge.srcs/sources_1/bd/AXI_Merge/ip/AXI_Merge_rst_ps7_0_0M_0/AXI_Merge_rst_ps7_0_0M_0.xci
# IP: The module: 'AXI_Merge_rst_ps7_0_0M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/marco/OneDrive/Desktop/Project - CopyOLD/Block_Design/AXI_Merge/AXI_Merge.gen/sources_1/bd/AXI_Merge/ip/AXI_Merge_rst_ps7_0_0M_0/AXI_Merge_rst_ps7_0_0M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Merge_rst_ps7_0_0M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marco/OneDrive/Desktop/Project - CopyOLD/Block_Design/AXI_Merge/AXI_Merge.gen/sources_1/bd/AXI_Merge/ip/AXI_Merge_rst_ps7_0_0M_0/AXI_Merge_rst_ps7_0_0M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Merge_rst_ps7_0_0M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/marco/OneDrive/Desktop/Project - CopyOLD/Block_Design/AXI_Merge/AXI_Merge.gen/sources_1/bd/AXI_Merge/ip/AXI_Merge_rst_ps7_0_0M_0/AXI_Merge_rst_ps7_0_0M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI_Merge_rst_ps7_0_0M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
