# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pynq-z2_v1.0.xdc/PYNQ-Z2 v1.0.xdc

# Block Designs: bd/AXI_Merge/AXI_Merge.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge || ORIG_REF_NAME==AXI_Merge} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_processing_system7_0_0/AXI_Merge_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_processing_system7_0_0 || ORIG_REF_NAME==AXI_Merge_processing_system7_0_0} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_axi_dma_0_0/AXI_Merge_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_axi_dma_0_0 || ORIG_REF_NAME==AXI_Merge_axi_dma_0_0} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_ps7_0_axi_periph_0/AXI_Merge_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_ps7_0_axi_periph_0 || ORIG_REF_NAME==AXI_Merge_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_rst_ps7_0_0M_0/AXI_Merge_rst_ps7_0_0M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_rst_ps7_0_0M_0 || ORIG_REF_NAME==AXI_Merge_rst_ps7_0_0M_0} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_xbar_0/AXI_Merge_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_xbar_0 || ORIG_REF_NAME==AXI_Merge_xbar_0} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_axi_mem_intercon_0/AXI_Merge_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_axi_mem_intercon_0 || ORIG_REF_NAME==AXI_Merge_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_AXI_FIFO_0_0/AXI_Merge_AXI_FIFO_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_AXI_FIFO_0_0 || ORIG_REF_NAME==AXI_Merge_AXI_FIFO_0_0} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_auto_pc_0/AXI_Merge_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_auto_pc_0 || ORIG_REF_NAME==AXI_Merge_auto_pc_0} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_auto_us_0/AXI_Merge_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_auto_us_0 || ORIG_REF_NAME==AXI_Merge_auto_us_0} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_auto_us_1/AXI_Merge_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_auto_us_1 || ORIG_REF_NAME==AXI_Merge_auto_us_1} -quiet] -quiet

# IP: bd/AXI_Merge/ip/AXI_Merge_auto_pc_1/AXI_Merge_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AXI_Merge_auto_pc_1 || ORIG_REF_NAME==AXI_Merge_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/marco/OneDrive/Desktop/Project - CopyOLD/Block_Design/AXI_Merge/AXI_Merge.gen/sources_1/bd/AXI_Merge/AXI_Merge_ooc.xdc
